:: run-everywhere.bat "npm i ..\..\parameters-js\makeproaudio-parameters-js-1.1.0-beta.12.tgz"
:: run-everywhere.bat "npm i ..\..\glue-feature-tools\makeproaudio-glue-feature-tools-0.0.19.tgz"
:: run-everywhere.bat "npm i ..\..\makehaus-nodered-lib\makeproaudio-makehaus-nodered-lib-1.1.0-beta.30.tgz && tsc"
:: run-everywhere.bat "npm i ..\..\glue-feature-tools\makeproaudio-glue-feature-tools-0.0.14.tgz"
:: run-everywhere.bat "npm i @makeproaudio/parameters-js@1.1.0-beta.9"
:: run-everywhere.bat "npm i @makeproaudio/makehaus-nodered-lib@1.1.0-beta.25"
:: run-everywhere.bat "npm i @makeproaudio/glue-feature-tools@0.0.15"
run-everywhere.bat "npm i @makeproaudio/parameters-js@1.1.0-beta.13 @makeproaudio/makehaus-nodered-lib@1.1.0-beta.31 @makeproaudio/glue-feature-tools@0.0.20 && tsc"
:: run-everywhere.bat "tsc"