:: run-everywhere.bat "npm i ..\..\glue-feature-tools\makeproaudio-glue-feature-tools-0.0.14.tgz"
:: run-everywhere.bat "npm i ..\..\makehaus-nodered-lib\makeproaudio-makehaus-nodered-lib-1.1.0-beta.21.tgz"
:: run-everywhere.bat "npm i ..\..\parameters-js\makeproaudio-parameters-js-1.1.0-beta.9.tgz"
:: run-everywhere.bat "npm i ..\..\glue-feature-tools\makeproaudio-glue-feature-tools-0.0.14.tgz"
:: run-everywhere.bat "npm i @makeproaudio/parameters-js@1.1.0-beta.9"
:: run-everywhere.bat "npm i @makeproaudio/glue-feature-tools@0.0.15"
run-everywhere.bat "tsc"